# SPDX-FileCopyrightText: Copyright DB Netz AG
# SPDX-License-Identifier: Apache-2.0

# TrackTypes
#
# Created:  2020-11-19
# Modified: 2020-11-19
# Version:  2.0
# Status:   Draft
#
# Description: List of distinct track types.

uint8 TRACK_TYPE_UNDEFINED = 0
uint8 TRACK_TYPE_RAIL      = 1
uint8 TRACK_TYPE_VIRTUAL   = 2

uint8 TRACK_SUBTYPE_UNDEFINED = 0
uint8 TRACK_SUBTYPE_LEFT      = 1
uint8 TRACK_SUBTYPE_RIGHT     = 2
uint8 TRACK_SUBTYPE_CENTER    = 3