# SPDX-FileCopyrightText: Copyright DB Netz AG
# SPDX-License-Identifier: Apache-2.0

# FieldOfView
#
# Created:  2020-04-20
# Modified: 2020-04-22
# Version:  2.0
# Status:   Consolidated
#
# Description: Representation of vertical and horizontal field of view.

# Vertical field of view
float64 vertical

#Horizontal field of view
float64 horizontal

# Distance from which on the FOV is valid
float64 distance_from

# Distance to which the FOV is valid
float64 distance_to