# SPDX-FileCopyrightText: Copyright DB Netz AG
# SPDX-License-Identifier: Apache-2.0

# RailHorizonData
#
# Created:  2020-06-12
# Modified: 2020-06-12
# Version:  2.0
# Status:   Draft
#
# Description: Provision of the rail horizon which provides imformation about the tracks, topology, and landmarks

# Tracks
Track[] tracks

# Topology of tracks
Topology topology_tracks

# Driving path
ID[] driving_path

# Landmarks
Object[] landmarks

# Zones
Object[] zones

# Optional attributes
KeyValueMap optional_attributes