# SPDX-FileCopyrightText: Copyright DB Netz AG
# SPDX-License-Identifier: Apache-2.0

# SensorInformation
#
# Created:  2020-04-08
# Modified: 2020-05-13
# Version:  2.0
# Status:   Consolidated
#
# Description: Definition of a sensor, its rough mounting position, and field of view(s). Can be as well multiple sensors in the case of sensor fusion.

# Sensor Information
SensorInformationEntry[] sensor_information