# SPDX-FileCopyrightText: Copyright DB Netz AG
# SPDX-License-Identifier: Apache-2.0

# StaticObjects
#
# Created:  2020-04-16
# Modified: 2020-04-22
# Version:  2.0
# Status:   Consolidated
#
# Description: Message type for providing information about static objects.

# Sensor information
SensorInformation sensor

# Sensor integrity
SensorIntegrity integrity

# List of static objects
Object[] objects

# Optional attributes
KeyValueMap optional_attributes